name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'website/**'
      - '.github/workflows/deploy.yml'

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          cd website
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website/dist # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
